export interface UserType {
    id: number,
    first_name: string,
    last_name: string,
    ci: string,
    email: string,
    phone: string,
    roleId: number,
    shopId: number,
    username: string,
    password_hash: string,
    createdAt: string,
    updatedAt: string,
    role: {
        id: number,
        name: string,
        view_dashboard: true,
        perms_dashboard: string,
        view_inventory: true,
        perms_inventory: string,
        view_transit: true,
        perms_transit: string,
        view_orders: true,
        perms_orders: string,
        view_finance: true,
        perms_finance: string,
        view_sales: true,
        perms_sales: string,
        view_box: true,
        perms_box: string,
        createdAt: string,
        updatedAt: string
    }
}